"""
Seed 30 demo tourist users for the /individual matching section.
Idempotent: re-running updates existing demo users without creating duplicates.
Does NOT touch existing non-demo users.

Usage:
    cd backend
    python seed_individual_users.py
"""

import os
import sys

os.environ.setdefault("SECRET_KEY", "dev-seed-secret-not-for-production-000000000000")
os.environ.setdefault("DATABASE_URL", "sqlite:///./atai_travel.db")

from app.database import SessionLocal
from app.models.user import User
from app.core.security import hash_password

DEMO_PASSWORD = "DemoUser123!"

DEMO_USERS = [
    {
        "email": "individual01@atai.demo",
        "full_name": "Айгерим Мамытова",
        "age": 26,
        "city": "Бишкек",
        "bio": "Обожаю горные маршруты и фотографию. Ищу попутчика для похода на Ала-Арчу этим летом.",
        "photo_url": "https://i.pravatar.cc/150?img=1",
        "status": "verified",
        "interests": "hiking,mountains,photography",
        "travel_style": "adventure",
        "budget_min": 200,
        "budget_max": 800,
        "languages": "ru,ky",
        "phone": "+996700010001",
        "telegram": "@aigerim_demo",
        "whatsapp": "+996700010001",
        "instagram": "@aigerim.travel",
    },
    {
        "email": "individual02@atai.demo",
        "full_name": "Тимур Садыков",
        "age": 31,
        "city": "Ош",
        "bio": "Путешествую по Центральной Азии уже 5 лет. Люблю историю и культуру. Готов показать Сулейман-Гору.",
        "photo_url": "https://i.pravatar.cc/150?img=2",
        "status": "active",
        "interests": "culture,history,food",
        "travel_style": "culture",
        "budget_min": 150,
        "budget_max": 600,
        "languages": "ru,ky,uz",
        "phone": "+996700010002",
        "telegram": "@timur_demo",
        "whatsapp": "+996700010002",
        "instagram": "@timur.osh",
    },
    {
        "email": "individual03@atai.demo",
        "full_name": "Зарина Исакова",
        "age": 24,
        "city": "Каракол",
        "bio": "Местная гид. Знаю все тропы вокруг Иссык-Куля. Ищу компанию для трекинга на Алтын-Арашан.",
        "photo_url": "https://i.pravatar.cc/150?img=3",
        "status": "verified",
        "interests": "trekking,lakes,camping",
        "travel_style": "adventure",
        "budget_min": 100,
        "budget_max": 500,
        "languages": "ru,ky,en",
        "phone": "+996700010003",
        "telegram": "@zarina_demo",
        "whatsapp": "+996700010003",
        "instagram": "@zarina.karakol",
    },
    {
        "email": "individual04@atai.demo",
        "full_name": "Бакыт Токтосунов",
        "age": 35,
        "city": "Нарын",
        "bio": "Конный туризм — моя страсть. Веду туры по Нарынской области на лошадях. Приглашаю разделить приключение.",
        "photo_url": "https://i.pravatar.cc/150?img=4",
        "status": "active",
        "interests": "horse_riding,nomad,mountains",
        "travel_style": "adventure",
        "budget_min": 300,
        "budget_max": 1200,
        "languages": "ru,ky",
        "phone": "+996700010004",
        "telegram": "@bakyt_demo",
        "whatsapp": "+996700010004",
        "instagram": "@bakyt.naryn",
    },
    {
        "email": "individual05@atai.demo",
        "full_name": "Нурзат Эргешова",
        "age": 28,
        "city": "Джалал-Абад",
        "bio": "Люблю купания в горячих источниках и спокойный отдых. Ищу попутчицу для тура по югу Кыргызстана.",
        "photo_url": "https://i.pravatar.cc/150?img=5",
        "status": "active",
        "interests": "relax,lakes,food",
        "travel_style": "relax",
        "budget_min": 100,
        "budget_max": 400,
        "languages": "ru,ky",
        "phone": "+996700010005",
        "telegram": "@nurzat_demo",
        "whatsapp": "+996700010005",
        "instagram": "@nurzat.travel",
    },
    {
        "email": "individual06@atai.demo",
        "full_name": "Алибек Жунусов",
        "age": 29,
        "city": "Талас",
        "bio": "Интересуюсь эпосом Манас и кочевой культурой. Веду блог о путешествиях по Кыргызстану.",
        "photo_url": "https://i.pravatar.cc/150?img=6",
        "status": "verified",
        "interests": "nomad,culture,history",
        "travel_style": "culture",
        "budget_min": 200,
        "budget_max": 700,
        "languages": "ru,ky,en",
        "phone": "+996700010006",
        "telegram": "@alibek_demo",
        "whatsapp": "+996700010006",
        "instagram": "@alibek.talas",
    },
    {
        "email": "individual07@atai.demo",
        "full_name": "Гульмира Абдиева",
        "age": 33,
        "city": "Баткен",
        "bio": "Работаю учителем, летом путешествую. Хочу исследовать Кара-Дарьинский каньон.",
        "photo_url": "https://i.pravatar.cc/150?img=7",
        "status": "active",
        "interests": "culture,hiking,food",
        "travel_style": "mixed",
        "budget_min": 80,
        "budget_max": 350,
        "languages": "ru,ky",
        "phone": "+996700010007",
        "telegram": "@gulmira_demo",
        "whatsapp": "+996700010007",
        "instagram": "@gulmira.batken",
    },
    {
        "email": "individual08@atai.demo",
        "full_name": "Данияр Омуров",
        "age": 27,
        "city": "Бишкек",
        "bio": "Рафтинг и сплавы по горным рекам — моё всё. Ищу команду для сплава по Чуй-Кеминскому маршруту.",
        "photo_url": "https://i.pravatar.cc/150?img=8",
        "status": "verified",
        "interests": "rafting,camping,mountains",
        "travel_style": "adventure",
        "budget_min": 250,
        "budget_max": 900,
        "languages": "ru,en",
        "phone": "+996700010008",
        "telegram": "@daniyar_demo",
        "whatsapp": "+996700010008",
        "instagram": "@daniyar.rafting",
    },
    {
        "email": "individual09@atai.demo",
        "full_name": "Аселя Токтогулова",
        "age": 22,
        "city": "Каракол",
        "bio": "Студентка, люблю бэкпекинг. Была в 12 странах. Теперь хочу глубже изучить родной Кыргызстан.",
        "photo_url": "https://i.pravatar.cc/150?img=9",
        "status": "active",
        "interests": "hiking,photography,camping",
        "travel_style": "adventure",
        "budget_min": 50,
        "budget_max": 300,
        "languages": "ru,ky,en",
        "phone": "+996700010009",
        "telegram": "@aselia_demo",
        "whatsapp": "+996700010009",
        "instagram": "@aselia.backpack",
    },
    {
        "email": "individual10@atai.demo",
        "full_name": "Манас Бекташев",
        "age": 38,
        "city": "Бишкек",
        "bio": "IT-предприниматель. Путешествую в деловых поездках и для отдыха. Ищу культурно-гастрономические туры.",
        "photo_url": "https://i.pravatar.cc/150?img=10",
        "status": "verified",
        "interests": "food,culture,history",
        "travel_style": "culture",
        "budget_min": 500,
        "budget_max": 2000,
        "languages": "ru,en",
        "phone": "+996700010010",
        "telegram": "@manas_demo",
        "whatsapp": "+996700010010",
        "instagram": "@manas.biz.travel",
    },
    {
        "email": "individual11@atai.demo",
        "full_name": "Sasha Petrov",
        "age": 30,
        "city": "Алматы",
        "bio": "Живу в Алматы, часто езжу в Кыргызстан на выходные. Люблю горы и треккинг. Ищу попутчиков.",
        "photo_url": "https://i.pravatar.cc/150?img=11",
        "status": "active",
        "interests": "trekking,mountains,camping",
        "travel_style": "adventure",
        "budget_min": 200,
        "budget_max": 800,
        "languages": "ru,en",
        "phone": "+77001010011",
        "telegram": "@sasha_demo",
        "whatsapp": "+77001010011",
        "instagram": "@sasha.almaty",
    },
    {
        "email": "individual12@atai.demo",
        "full_name": "Дина Нурланова",
        "age": 25,
        "city": "Астана",
        "bio": "Дизайнер интерьеров из Астаны. Мечтаю увидеть юрты в реальном кочевом стиле. Люблю фото.",
        "photo_url": "https://i.pravatar.cc/150?img=12",
        "status": "active",
        "interests": "nomad,photography,culture",
        "travel_style": "culture",
        "budget_min": 300,
        "budget_max": 1000,
        "languages": "ru,en",
        "phone": "+77001010012",
        "telegram": "@dina_demo",
        "whatsapp": "+77001010012",
        "instagram": "@dina.design.travel",
    },
    {
        "email": "individual13@atai.demo",
        "full_name": "Umid Rashidov",
        "age": 32,
        "city": "Ташкент",
        "bio": "Из Ташкента, люблю путешествовать по Шёлковому пути. Ищу компанию для поездки в Ош и Узген.",
        "photo_url": "https://i.pravatar.cc/150?img=13",
        "status": "active",
        "interests": "history,culture,food",
        "travel_style": "culture",
        "budget_min": 150,
        "budget_max": 600,
        "languages": "uz,ru,en",
        "phone": "+998901010013",
        "telegram": "@umid_demo",
        "whatsapp": "+998901010013",
        "instagram": "@umid.silk.road",
    },
    {
        "email": "individual14@atai.demo",
        "full_name": "Emily Clark",
        "age": 27,
        "city": "London",
        "bio": "Travel blogger from London. Writing about Central Asia. Looking for local guides and companions.",
        "photo_url": "https://i.pravatar.cc/150?img=14",
        "status": "verified",
        "interests": "photography,culture,food",
        "travel_style": "mixed",
        "budget_min": 500,
        "budget_max": 2500,
        "languages": "en",
        "phone": "+441010101014",
        "telegram": "@emily_demo",
        "whatsapp": "+441010101014",
        "instagram": "@emily.central.asia",
    },
    {
        "email": "individual15@atai.demo",
        "full_name": "Lukas Müller",
        "age": 34,
        "city": "Berlin",
        "bio": "Aventurer from Berlin. Planning a 3-week trekking trip through Tian Shan. Need local insights!",
        "photo_url": "https://i.pravatar.cc/150?img=15",
        "status": "active",
        "interests": "trekking,mountains,camping",
        "travel_style": "adventure",
        "budget_min": 600,
        "budget_max": 3000,
        "languages": "de,en",
        "phone": "+491510101015",
        "telegram": "@lukas_demo",
        "whatsapp": "+491510101015",
        "instagram": "@lukas.tian.shan",
    },
    {
        "email": "individual16@atai.demo",
        "full_name": "Чолпон Бакытбекова",
        "age": 23,
        "city": "Бишкек",
        "bio": "Студентка КРСУ. Интересуюсь этнотуризмом и сохранением традиций. Участвую в фестивалях.",
        "photo_url": "https://i.pravatar.cc/150?img=16",
        "status": "active",
        "interests": "nomad,culture,history",
        "travel_style": "culture",
        "budget_min": 60,
        "budget_max": 250,
        "languages": "ru,ky",
        "phone": "+996700010016",
        "telegram": "@cholpon_demo",
        "whatsapp": "+996700010016",
        "instagram": "@cholpon.ethno",
    },
    {
        "email": "individual17@atai.demo",
        "full_name": "Руслан Кадыров",
        "age": 40,
        "city": "Ош",
        "bio": "Врач на пенсии. Теперь путешествую и собираю лекарственные растения Памирского хребта.",
        "photo_url": "https://i.pravatar.cc/150?img=17",
        "status": "verified",
        "interests": "mountains,hiking,culture",
        "travel_style": "mixed",
        "budget_min": 200,
        "budget_max": 800,
        "languages": "ru,ky",
        "phone": "+996700010017",
        "telegram": "@ruslan_demo",
        "whatsapp": "+996700010017",
        "instagram": "@ruslan.pamir",
    },
    {
        "email": "individual18@atai.demo",
        "full_name": "Медина Алиева",
        "age": 29,
        "city": "Джалал-Абад",
        "bio": "Люблю термальные источники Арсланбоба. Каждое лето организую небольшие группы от 3 до 6 человек.",
        "photo_url": "https://i.pravatar.cc/150?img=18",
        "status": "active",
        "interests": "relax,lakes,food",
        "travel_style": "relax",
        "budget_min": 120,
        "budget_max": 450,
        "languages": "ru,ky",
        "phone": "+996700010018",
        "telegram": "@medina_demo",
        "whatsapp": "+996700010018",
        "instagram": "@medina.arslanbob",
    },
    {
        "email": "individual19@atai.demo",
        "full_name": "Жолдош Осмонов",
        "age": 36,
        "city": "Нарын",
        "bio": "Охотник и следопыт. Знаю горы Нарынской области как свои пять пальцев. Вожу на сафари.",
        "photo_url": "https://i.pravatar.cc/150?img=19",
        "status": "active",
        "interests": "camping,mountains,horse_riding",
        "travel_style": "adventure",
        "budget_min": 300,
        "budget_max": 1500,
        "languages": "ru,ky",
        "phone": "+996700010019",
        "telegram": "@zholdosh_demo",
        "whatsapp": "+996700010019",
        "instagram": "@zholdosh.naryn",
    },
    {
        "email": "individual20@atai.demo",
        "full_name": "Венера Исмаилова",
        "age": 26,
        "city": "Бишкек",
        "bio": "Организатор йога-ретритов на берегу Иссык-Куля. Ищу единомышленников для медитации в горах.",
        "photo_url": "https://i.pravatar.cc/150?img=20",
        "status": "verified",
        "interests": "relax,lakes,mountains",
        "travel_style": "relax",
        "budget_min": 200,
        "budget_max": 700,
        "languages": "ru,en",
        "phone": "+996700010020",
        "telegram": "@venera_demo",
        "whatsapp": "+996700010020",
        "instagram": "@venera.yoga.kg",
    },
    {
        "email": "individual21@atai.demo",
        "full_name": "Арген Кенешов",
        "age": 21,
        "city": "Каракол",
        "bio": "Студент-географ. Изучаю ледники Тянь-Шаня. Ищу попутчиков для научно-туристических экспедиций.",
        "photo_url": "https://i.pravatar.cc/150?img=21",
        "status": "active",
        "interests": "mountains,trekking,photography",
        "travel_style": "adventure",
        "budget_min": 50,
        "budget_max": 300,
        "languages": "ru,ky,en",
        "phone": "+996700010021",
        "telegram": "@argen_demo",
        "whatsapp": "+996700010021",
        "instagram": "@argen.glacier",
    },
    {
        "email": "individual22@atai.demo",
        "full_name": "Светлана Ковалёва",
        "age": 44,
        "city": "Алматы",
        "bio": "Преподаватель истории из Алматы. Обожаю петроглифы Саймалуу-Таша. Ищу спокойный тур.",
        "photo_url": "https://i.pravatar.cc/150?img=22",
        "status": "active",
        "interests": "history,culture,photography",
        "travel_style": "culture",
        "budget_min": 300,
        "budget_max": 1200,
        "languages": "ru,en",
        "phone": "+77001010022",
        "telegram": "@svetlana_demo",
        "whatsapp": "+77001010022",
        "instagram": "@svetlana.history",
    },
    {
        "email": "individual23@atai.demo",
        "full_name": "Калысбек Мамаев",
        "age": 45,
        "city": "Талас",
        "bio": "Фермер и охотник. В сезон вожу туристов на охоту в Таласской долине. Уютный кемпинг гарантирован.",
        "photo_url": "https://i.pravatar.cc/150?img=23",
        "status": "active",
        "interests": "camping,nomad,horse_riding",
        "travel_style": "adventure",
        "budget_min": 150,
        "budget_max": 600,
        "languages": "ru,ky",
        "phone": "+996700010023",
        "telegram": "@kalysbek_demo",
        "whatsapp": "+996700010023",
        "instagram": "@kalysbek.talas",
    },
    {
        "email": "individual24@atai.demo",
        "full_name": "Айша Дуйшеева",
        "age": 31,
        "city": "Бишкек",
        "bio": "Фудблогер. Путешествую ради кухни. Обожаю самсу, курут, бешбармак. Ищу гастротуры.",
        "photo_url": "https://i.pravatar.cc/150?img=24",
        "status": "verified",
        "interests": "food,culture,photography",
        "travel_style": "culture",
        "budget_min": 150,
        "budget_max": 600,
        "languages": "ru,ky,en",
        "phone": "+996700010024",
        "telegram": "@aisha_demo",
        "whatsapp": "+996700010024",
        "instagram": "@aisha.foodblog",
    },
    {
        "email": "individual25@atai.demo",
        "full_name": "Нурлан Токтоматов",
        "age": 37,
        "city": "Бишкек",
        "bio": "Альпинист. Покорял пик Победы. Ищу партнёров для восхождения на пик Ленина.",
        "photo_url": "https://i.pravatar.cc/150?img=25",
        "status": "verified",
        "interests": "mountains,trekking,camping",
        "travel_style": "adventure",
        "budget_min": 500,
        "budget_max": 3000,
        "languages": "ru,ky,en",
        "phone": "+996700010025",
        "telegram": "@nurlan_demo",
        "whatsapp": "+996700010025",
        "instagram": "@nurlan.alpinist",
    },
    {
        "email": "individual26@atai.demo",
        "full_name": "Maria Santos",
        "age": 29,
        "city": "Berlin",
        "bio": "Photographer and documentary filmmaker from Portugal, based in Berlin. Documenting nomadic cultures.",
        "photo_url": "https://i.pravatar.cc/150?img=26",
        "status": "active",
        "interests": "photography,nomad,culture",
        "travel_style": "mixed",
        "budget_min": 400,
        "budget_max": 2000,
        "languages": "en,de,pt",
        "phone": "+491510101026",
        "telegram": "@maria_demo",
        "whatsapp": "+491510101026",
        "instagram": "@maria.nomadic.lens",
    },
    {
        "email": "individual27@atai.demo",
        "full_name": "James Wilson",
        "age": 42,
        "city": "London",
        "bio": "Retired army officer. Now doing long-distance hikes around the world. Kyrgyzstan is next on my list.",
        "photo_url": "https://i.pravatar.cc/150?img=27",
        "status": "active",
        "interests": "hiking,mountains,camping",
        "travel_style": "adventure",
        "budget_min": 700,
        "budget_max": 3500,
        "languages": "en",
        "phone": "+441010101027",
        "telegram": "@james_demo",
        "whatsapp": "+441010101027",
        "instagram": "@james.hiker",
    },
    {
        "email": "individual28@atai.demo",
        "full_name": "Феруза Назарова",
        "age": 28,
        "city": "Ташкент",
        "bio": "Узбекский дизайнер одежды. Изучаю традиционные орнаменты Кыргызстана для новой коллекции.",
        "photo_url": "https://i.pravatar.cc/150?img=28",
        "status": "active",
        "interests": "culture,history,photography",
        "travel_style": "culture",
        "budget_min": 200,
        "budget_max": 700,
        "languages": "uz,ru,en",
        "phone": "+998901010028",
        "telegram": "@feruza_demo",
        "whatsapp": "+998901010028",
        "instagram": "@feruza.design",
    },
    {
        "email": "individual29@atai.demo",
        "full_name": "Бегайым Эсенбекова",
        "age": 20,
        "city": "Каракол",
        "bio": "Активный образ жизни — моя религия. Горные велотуры, сноуборд, рафтинг. Всё что с адреналином!",
        "photo_url": "https://i.pravatar.cc/150?img=29",
        "status": "active",
        "interests": "rafting,mountains,camping",
        "travel_style": "adventure",
        "budget_min": 80,
        "budget_max": 400,
        "languages": "ru,ky,en",
        "phone": "+996700010029",
        "telegram": "@begaim_demo",
        "whatsapp": "+996700010029",
        "instagram": "@begaim.extreme",
    },
    {
        "email": "individual30@atai.demo",
        "full_name": "Мирлан Суйунбеков",
        "age": 50,
        "city": "Бишкек",
        "bio": "Писатель и журналист. Пишу книгу о Великом Шёлковом пути через Кыргызстан. Ищу местных рассказчиков.",
        "photo_url": "https://i.pravatar.cc/150?img=30",
        "status": "verified",
        "interests": "history,culture,nomad",
        "travel_style": "culture",
        "budget_min": 400,
        "budget_max": 1500,
        "languages": "ru,ky,en",
        "phone": "+996700010030",
        "telegram": "@mirlan_demo",
        "whatsapp": "+996700010030",
        "instagram": "@mirlan.writer",
    },
]


def seed():
    db = SessionLocal()
    created = 0
    updated = 0

    try:
        pwd_hash = hash_password(DEMO_PASSWORD)

        for data in DEMO_USERS:
            user = db.query(User).filter(User.email == data["email"]).first()
            if user is None:
                user = User(
                    email=data["email"],
                    password_hash=pwd_hash,
                    role="tourist",
                )
                db.add(user)
                created += 1
            else:
                updated += 1

            user.password_hash = pwd_hash
            user.full_name    = data["full_name"]
            user.age          = data["age"]
            user.city         = data["city"]
            user.bio          = data["bio"]
            user.photo_url    = data["photo_url"]
            user.role         = "tourist"
            user.status       = data["status"]
            user.interests    = data["interests"]
            user.travel_style = data["travel_style"]
            user.budget_min   = data["budget_min"]
            user.budget_max   = data["budget_max"]
            user.languages    = data["languages"]
            user.phone        = data["phone"]
            user.telegram     = data["telegram"]
            user.whatsapp     = data["whatsapp"]
            user.instagram    = data["instagram"]

        db.commit()
    finally:
        db.close()

    print("\nDemo individual users created/updated successfully")
    print(f"  Created : {created}")
    print(f"  Updated : {updated}")
    print(f"  Total   : {created + updated}\n")

    col_w = 32
    print(f"{'Email':<{col_w}} {'Password'}")
    print("-" * (col_w + 16))
    for data in DEMO_USERS:
        print(f"{data['email']:<{col_w}} {DEMO_PASSWORD}")


if __name__ == "__main__":
    seed()
