const labels = {
  '1': '1 день',
  '2-3': '2–3 дня',
  '4-6': '4–6 дней',
  '7-10': '7–10 дней',
  '10+': 'Больше 10 дней',
  unknown: 'Пока не знаю',
  solo: 'Один/одна',
  couple: 'С парой',
  friends: 'С друзьями',
  family: 'С семьёй',
  kids: 'С детьми',
  group: 'С группой',
  nature: 'Природа',
  mountains: 'Горы',
  lakes: 'Озёра',
  culture: 'Культура и история',
  active: 'Активный отдых',
  relax: 'Спокойный отдых',
  photo: 'Фото и контент',
  food: 'Гастрономия',
  nomad: 'Кочевая культура',
  day_trip: 'Однодневная поездка',
  short_tour: 'Тур на 2–3 дня',
  week_route: 'Недельный маршрут',
  trekking: 'Поход/треккинг',
  comfortable: 'Комфортный тур',
  budget: 'Бюджетное путешествие',
  calm: 'Спокойный и красивый',
  active_soft: 'Активный, но без перегруза',
  adventure: 'Приключенческий',
  learning: 'Познавательный',
  romantic: 'Романтичный',
  easy: 'Лёгкий',
  moderate: 'Средний',
  hard: 'Сложный',
  extreme: 'Экстремальный',
  economy: 'Эконом',
  middle: 'Средний',
  comfort: 'Комфорт',
  premium: 'Премиум',
  spring: 'Весна',
  summer: 'Лето',
  autumn: 'Осень',
  winter: 'Зима',
  recommend: 'Хочу рекомендацию',
  simple: 'Недорого и просто',
  clean: 'Чисто и удобно',
  yurt: 'Юрты и местный колорит',
  hotel: 'Отель или гостевой дом',
  any: 'Не важно',
  car: 'Легковая машина',
  minivan: 'Минивэн',
  bus: 'Групповой автобус',
  walking: 'Пеший маршрут',
  beach: 'Пляжный отдых',
  walks: 'Лёгкие прогулки',
  horse: 'Конные прогулки',
  rafting: 'Рафтинг',
  hot_springs: 'Горячие источники',
  history: 'Исторические места',
  photo_tour: 'Фототур',
  '1h': 'До 1 часа',
  '2-4h': '2–4 часа',
  '5-8h': '5–8 часов',
  full_day: 'Можно ехать целый день',
  remote: 'Готов/готова к удалённым местам',
  beautiful_views: 'Красивые виды',
  price: 'Цена',
  safety: 'Безопасность',
  unique: 'Уникальный опыт',
  slow: 'Отдых без спешки',
}

export function travelLabel(value) {
  return labels[value] || value || 'Не указано'
}

export function travelLabels(values) {
  return values.map((value) => travelLabel(value))
}
